version: "3"

services:
  php:
    container_name: ${PROJECT_NAME}_${PHP_CONTAINER_NAME}
    build:
      context: ./
      dockerfile: "docker/configs/php/Dockerfile"
      args:
        - WORKDIR=$WORKDIR
    volumes:
      - ./app:${WORKDIR}
      - ./app/bin:/var/www/public
    env_file:
      - .env
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    container_name: ${PROJECT_NAME}_${NGINX_CONTAINER_NAME}
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/configs/nginx/conf.d:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx:/var/log/nginx
      - ./app/bin:/var/www/public
    networks:
      - app-network

networks:
  app-network:
    driver: bridge