version: "3"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network

  php:
    container_name: ${PROJECT_NAME}_${PHP_CONTAINER_NAME}
    build:
      context: ./
      dockerfile: "docker/configs/php/Dockerfile"
      args:
        - WORKDIR=$WORKDIR
    volumes:
      - ./app:${WORKDIR}
      - ./app/bin:/var/www/public
    env_file:
      - .env
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

  nginx:
    container_name: ${PROJECT_NAME}_${NGINX_CONTAINER_NAME}
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/configs/nginx/conf.d:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx:/var/log/nginx
      - ./app/bin:/var/www/public
    networks:
      - app-network

networks:
  app-network:
    driver: bridge